services:
    react_app:
        image: node:lts-slim
        volumes:
            - ./react_clerk:/app
        env_file:
            - .env
        ports:
            - 5173:5173
        working_dir: /app
        command: sh -c "npm run dev -- --host"